In [1]:
import torch

# 1

In [2]:
a = torch.tensor(list(range(9)))

In [3]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
a.shape

torch.Size([9])

In [8]:
a.storage_offset()

0

In [9]:
a.stride()

(1,)

## (a)

In [10]:
b = a.view(3, 3)

In [11]:
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

viewは3\*3のテンソルに変換している

In [12]:
id(a.storage()) == id(b.storage())

True

## (b)

In [13]:
c = b[1:, 1:]

In [14]:
c.shape

torch.Size([2, 2])

In [15]:
c.storage_offset()

4

In [16]:
c.stride()

(3, 1)

# 2

cosine: torch.cos(input)  
square root: torch.sqrt(input)

## (a)

float型ではエラーが出る

In [18]:
torch.cos(float(a[2]))

TypeError: cos(): argument 'input' (position 1) must be Tensor, not float

tensor型に対して実行

In [19]:
torch.cos(a)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

## (b)

tensor型ならいいので、tensor型で要素を抽出すれば問題ない

In [20]:
torch.cos(a[2])

tensor(-0.4161)

場合によってはfloatに変換する

In [21]:
float(torch.cos(a[2]))

-0.416146844625473

## (c)

正規化する関数

In [24]:
def normalize(a: torch.tensor) -> torch.tensor:
    a = a.double()
    return (a - torch.mean(a))/torch.sqrt(torch.var(a))

In [25]:
normalize(a)

tensor([-1.4606, -1.0954, -0.7303, -0.3651,  0.0000,  0.3651,  0.7303,  1.0954,
         1.4606], dtype=torch.float64)